// frontend/src/app/(admin)/admin/(auth)/login/page.tsx
"use client";
import Brand from "@/components/Brand";
import { useQuery } from "@apollo/experimental-nextjs-app-support/ssr";
import { gql, useMutation } from "@apollo/client";
import { useFormik } from "formik";
import * as Yup from "yup";

const Page = () => {
  const mu = useMutation();
  const formik = useFormik({
    initialValues: {
      email: "",
      password: "",
    },
    validationSchema: Yup.object({
      email: Yup.string().email("Must be an email").required("Required"),
      password: Yup.string()
        .required("Required")
        .min(8, "Password must have 8 charectors"),
    }),
    onSubmit: async (values) => {
      console.log("ran");

      const query = gql`
        query Now {
          now(id: "1")
        }
      `;

      console.log(mu);
    },
  });

  return (
    <div className='flex flex-col md:flex-row h-screen p-10  text-slate bg-secondary bg-opacity-10'>
      <div className='w-full flex justify-center items-center p-16'>
        <form
          className='text-start space-y-2 max-w-lg border-2 bg-white rounded-lg p-8 shadow-2xl'
          onSubmit={(e) => {
            e.preventDefault();
            formik.handleSubmit();
          }}
        >
          <Brand />
          <h1 className='text-xl font-bold text-center'>Welcome back!</h1>
          <p className='text-slate-600'>
            Please sign in to your account and start the adventure
          </p>
          <div className='form-control w-full'>
            <label htmlFor='email'>Email</label>
            <input
              type='text'
              name='email'
              placeholder='Type here'
              className='input input-bordered w-full'
              value={formik.values.email}
              onChange={formik.handleChange}
            />
            <span className='text-red-500'>
              {formik.errors.email && formik.errors.email}
            </span>
          </div>
          <div className='form-control w-full'>
            <label htmlFor='password'>Password</label>
            <input
              type='password'
              name='password'
              placeholder='Type here'
              className='input input-bordered w-full'
              value={formik.values.password}
              onChange={formik.handleChange}
            />
            <span className='text-red-500'>
              {formik.errors.password && formik.errors.password}
            </span>
          </div>
          <div className='form-control'>
            <label className='label cursor-pointer flex justify-start gap-3'>
              <input
                type='checkbox'
                className='checkbox checkbox-primary'
                name='remember_me'
              />
              <span className='label-text'>Remember me</span>
            </label>
          </div>
          <button type='submit' className='btn btn-primary w-full'>
            Sign in
          </button>
        </form>
      </div>
    </div>
  );
};

export default Page;

// client/pages/admin/login.vue
<script setup lang="ts">
import { Icon } from "#components";
import useAuthStore from "~/store/useAuthStroe";

const query = gql`
  query {
    adminUsers {
      firstName
    }
  }
`;

// const { mutate } = useMutation(query);

definePageMeta({
  // middleware: ["guest"],
});

const authStore = useAuthStore();
const visible = useState("visible", () => false);

const EyeOpenIcon = h(Icon, {
  name: "material-symbols:visibility-outline-rounded",
});
const MailIcon = h(Icon, {
  name: "mdi-email-outline",
});
const EyeCloseIcon = h(Icon, {
  name: "material-symbols:visibility-off-outline",
});

const LockIcon = h(Icon, {
  name: "mdi-lock-outline",
});

const email = useState("email", () => "");
const password = useState("password", () => "");

const login = async () => {
  console.log("ran");
  const { result, refetch } = useQuery(query);
  console.log(result);
  refetch();
};
</script>

<template>
  <div
    class="flex flex-col md:flex-row h-screen p-10 text-slate bg-secondary bg-opacity-10"
  >
    <div class="w-full flex justify-center items-center p-16">
      <form
        class="text-start space-y-2 max-w-lg border-2 bg-white rounded-lg p-8 shadow-2xl"
        @submit.prevent="login"
      >
        <!-- <Brand /> -->
        <h1 class="text-xl font-bold text-center">Welcome back!</h1>
        <p class="text-slate-600">
          Please sign in to your account and start the adventure
        </p>
        <div class="form-control w-full">
          <label htmlFor="email">Email</label>
          <input
            type="text"
            name="email"
            placeholder="Type here"
            class="input input-bordered w-full"
          />
        </div>
        <div class="form-control w-full">
          <label htmlFor="password">Password</label>
          <input
            type="password"
            name="password"
            placeholder="Type here"
            class="input input-bordered w-full"
          />
          <span class="text-red-500"> </span>
        </div>
        <div class="form-control">
          <label class="label cursor-pointer flex justify-start gap-3">
            <input
              type="checkbox"
              class="checkbox checkbox-primary"
              name="remember_me"
            />
            <span class="label-text">Remember me</span>
          </label>
        </div>
        <button type="submit" class="btn btn-primary w-full">Sign in</button>
      </form>
    </div>
  </div>
</template>
